### ISSUE TITLE
SequenceBase Equals() problem

### ISSUE THREAD

**Issue by jstorch** [gmamaladze/globalmousekeyhook#101]
I believe there is a bug in SequenceBase's Equality checking.

SequenceBase.cs - Line 67 - The return is casting to a `Combination` object instead of `SequenceBase<T>` and throwing an System.InvalidCastException

**Comment by gmamaladze** [comment]
Makes sense. Feel free to fork, fix and create a merge request.

**Comment by gmamaladze** [comment]
Fixed by 44b46f57e07d90ec537fa04118632fe7cacd4ffa
