### ISSUE TITLE
How to unset combination

### ISSUE THREAD

**Issue by Nappyy** [gmamaladze/globalmousekeyhook#115]
I'd like to unset a key combination.

Let's say I installed a combination [CTRL] + [K]:
`Hook.GlobalEvents().OnCombination(new Dictionary<Combination, Action> {
                {Combination.TriggeredBy(Keys.K).With(Keys.Control), () => {
                    DoSomething(("K"));
                    }
                }
            });`

How can I unset this key combination at a later time?

**Comment by jonjonsson** [comment]
Hey Nappyy, did you figure this one out?
