### ISSUE TITLE
Is there a way to detect when ctrl is pressed?

### ISSUE THREAD

**Issue by Eliasyoussef47** [gmamaladze/globalmousekeyhook#142]
I want to globaly detect when ctrl is pressed (just the Control key. No other combinations.) And the example in the [README](https://github.com/gmamaladze/globalmousekeyhook/blob/vNext/README.md), [keycomb](https://github.com/gmamaladze/globalmousekeyhook/blob/vNext/keycomb.md) and #41 don't work.

Is this possible?

**Comment by Eliasyoussef47** [comment]
I figured it out. You can detect ctrl with IKeyboardEvents.KeyDown and IKeyboardEvents.KeyUp but not IKeyboardEvents.KeyPress.
This is in IKeyboardEvents.cs:

> The KeyPress event is not raised by non-character keys; however, the non-character keys do raise the KeyDown and KeyUp events.

**Comment by anastasiosskg** [comment]
Is there any example code how to detect left -> ALT CTRL SHIFT?
