### ISSUE TITLE
Add hotkey support to detect key combinations like Ctrl+Shift+u etc.

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/globalmousekeyhook#15]
Evtl. API https://msdn.microsoft.com/en-us/library/ms646309(VS.85).aspx can be used.

**Comment by PandaWood** [comment]
Certainly a good idea. I'm only here because I was hoping this library included this feature.
Anyone who wants to add their own shortcut keys in an Office addin (VSTO) will need this feature.

**Comment by PandaWood** [comment]
I see this is being worked on?
https://github.com/gmamaladze/globalmousekeyhook/tree/vNext/MouseKeyHook/HotKeys

**Comment by mischaherbrand** [comment]
![image](https://cloud.githubusercontent.com/assets/14272592/19276181/de063732-8fd5-11e6-9d54-619cb8878766.png)
It doesn't seem to work for me. Any ideas? I'm using the version 5.3.0

**Comment by caschw** [comment]
Here is how I'm using it.

`public MyAwesomeClassConstructor()
{
    _keyboardListener = new KeyboardHookListener(new GlobalHooker()) {Enabled = true};
    _keyboardListener.KeyDown += _keyboardListener_KeyDown;
}`

And then, handling the event:

`private void _keyboardListener_KeyDown(object sender, KeyEventArgs e)
{
    // Your Code here.
    // This is where I got my screenshot above
}`

**Comment by mischaherbrand** [comment]
I used the wrong handler (KeyPress instead of KeyDown). Thanks for your help!

**Comment by gmamaladze** [comment]
close 99ed5a40edb3e851d3bb23f6024aa622158a9bb2
