### ISSUE TITLE
Hook dont work everywhere

### ISSUE THREAD

**Issue by GAMELASTER** [gmamaladze/globalmousekeyhook#31]
Hello,

i want to use Hook at DirectX game, but on that the events are not executed...

Any ideas why no? :/

**Comment by gmamaladze** [comment]
Some programs typically games themselves use hooks to interact with keyboard. In this case they hook is ahead of yours and you did not get it. Some others e.g. MS Office Apps have similar issues too.   See: http://stackoverflow.com/questions/31054486/c-sharp-mousekeyhook-key-suppression-problems

**Comment by danielarakaki** [comment]
Hi,

is there some issue about this ?

Because i have the same problem with program Visual Studio of Microsoft.

**Comment by gmamaladze** [comment]
Are you setting a breakpoint inside hook callback in Visual Studio? If yes, then that's the problem. Hook callbacks will terminate and unsubscribe if not executed in very short time period dedicated.

**Comment by danielarakaki** [comment]
No, I'm only writing code in visual studio in a differente project. But the program that use globalmousekeyhook doesn't recognize the tap of keyboard.
