### ISSUE TITLE
Get Error: Using Barcode Reader

### ISSUE THREAD

**Issue by Skforu2005** [gmamaladze/globalmousekeyhook#32]
When I upgrade the library with the latest release then I am getting following error: CallbackOnCollectedDelegate was detected
Message: A callback was made on a garbage collected delegate of type 'Gma.System.MouseKeyHook!Gma.System.MouseKeyHook.WinApi.HookProcedure::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.

Please anyone help me to resolve the above issue.

**Comment by Skforu2005** [comment]
Problem was inside calling application not inside globalmousekeyhook.

**Comment by Fisher-Joe** [comment]
me too.
