### ISSUE TITLE
Not possible to capture accented characters correctly

### ISSUE THREAD

**Issue by Urutar** [gmamaladze/globalmousekeyhook#4]
It is currently not possible to capture special characters correctly, such as accents (á â à etc.).

If I try to write ^ and then a in notepad, only a is written instead of â.

This happens when using global keyhooks, thus preventing the user from writing characters with accents.

**Comment by Urutar** [comment]
This problem occurs due to usage of ToAscii, ToAsciiEx, ToUnicode or ToUnicodeEx since they mess up the keyboard state.

A possible solution to this problem can be found here:
https://gist.github.com/Ciantic/471698

**Comment by gmamaladze** [comment]
@Urutar Thanks for suggestion. Looks good. I'll take care of it.

**Comment by Urutar** [comment]
If the demo is running and I try to write â in notepad, only a is written.
This still happens in the current release.

**Comment by gmamaladze** [comment]
@Urutar Are you using Global or Application hooks? In Global hooks the issue should be gone.

**Comment by MaxXor** [comment]
I'm having the same problem.

**Comment by d3agle** [comment]
The problem is debugged here: https://infexia.wordpress.com/2012/07/20/deadchar-dead/

**Comment by yankejustin** [comment]
@gmamaladze We are using global hooks.

**Comment by gmamaladze** [comment]
Verified. Fixed.
