### ISSUE TITLE
Add hotkey support for modifier keys (especially Alt)

### ISSUE THREAD

**Issue by tuturto** [gmamaladze/globalmousekeyhook#41]
As far as I can tell, it's not possible to use Alt key in a same way as other keys shown in example: https://github.com/gmamaladze/globalmousekeyhook/blob/master/MouseKeyHook/HotKeys/ReadMe.txt

I get an argument out of range exception thrown from https://github.com/gmamaladze/globalmousekeyhook/blob/913b710bc3881d9fffe8c9003786f99e70dcc90c/MouseKeyHook/Implementation/KeyboardState.cs#L94 if I try to use Alt.

Or is there a way to detect that Alt is being pressed together with some other key?

**Comment by AxDSan** [comment]
I'm probably way too late for this but anyways... You can achieve this yourself:

As specified here: https://msdn.microsoft.com/en-us/library/yazd4ct6(v=vs.110).aspx

`
public void TextBox1_KeyPress(object sender, KeyPressEventArgs e)
{
	if ((Control.ModifierKeys & Keys.Shift) == Keys.Shift)
	{
		MessageBox.Show("Pressed " + Keys.Shift);
	}
}
`

So on your [GlobalHookKeyPress] event, you can simply put the body of the code above into such event and you will be able to pick up modifiers, To change modifiers to ALT or CTRL simply change it like so:
`
before: ((Control.ModifierKeys & Keys.Shift) == Keys.Shift)
after:  ((Control.ModifierKeys & Keys.Control) == Keys.Control)
`

**Comment by gmamaladze** [comment]
Closed by 99ed5a40edb3e851d3bb23f6024aa622158a9bb2
