### ISSUE TITLE
Non alphanumeric keydown returns wrong character

### ISSUE THREAD

**Issue by Liano** [gmamaladze/globalmousekeyhook#44]
Hello,
When I press a non alphanumeric character in the keyboard I get different character. ex
'.' returns  '¾'	(190)
'=' returns  '»' (187)
'\' returns  'Ü' (220)
my current keyboard layout is en-US, and using keydown event
Is this behavior normal?

**Comment by gmamaladze** [comment]
No. It should not behave like this. There must be some mistake. Is demo app working correctly in your environment?

**Comment by Liano** [comment]
The demo application works fine, I think maybe I using an older version of the library, let me update it and give you feedback afterward

**Comment by Liano** [comment]
I still get the same problem using even the latest version, what I noticed is that `KeyEventArgsExt` returns wrong character but `KeyPressEventArgsExt` returns the correct one.

**Comment by gmamaladze** [comment]
It is not a bug. The issue will be closed. The problem is the way you are using the component. To get support from community. Please post your question in StackOverflow http://stackoverflow.com/questions/tagged/mousekeyhook #close
