### ISSUE TITLE
Auto-repeat does not fire any events

### ISSUE THREAD

**Issue by Shujee** [gmamaladze/globalmousekeyhook#45]
If I press the RIGHT arrow key and keep it down without releasing, KeyDown event is fired just once. Even though the RIGHT arrow key keeps repeating, no more events (neither KeyDown, nor KeyPress) are ever fired. Is that by design or what?

Code to reproduce is simple:

    IKeyboardMouseEvents Hook = Gma.System.MouseKeyHook.Hook.AppEvents();
    private void main()
    {
      Hook.KeyDown += Hook_KeyDown;
      Hook.KeyPress += Hook_KeyPress;
      Hook.KeyUp += Hook_KeyUp;
    }

    private void Hook_KeyDown(object sender, System.Windows.Forms.KeyEventArgs e)
    {
      Console.WriteLine("DOWN");
    }

    private void Hook_KeyPress(object sender, System.Windows.Forms.KeyPressEventArgs e)
    {
      Console.WriteLine("PRESS");
    }

    private void Hook_KeyUp(object sender, System.Windows.Forms.KeyEventArgs e)
    {
      Console.WriteLine("UP");    
    }

**Comment by Shujee** [comment]
Digging this further I found out that the problem occurs only with the application hooks, not global hooks. To reproduce, simply run the demo app (of this project) and choose "application hook" radio button. Now click in the textbox area below (just to shift focus there) and press and hold the RIGHT arrow key on your keyboard. You'll see that it will register just one occurrance of KeyDown, nothing else. Now repeat the same process with global hook and you'll see that it registers multiple KeyDown events while u keep the RIGHT arrow key down.

The problem appears to be related to the following line (KeyEventArgsExt.cs: Line 72):

    bool isKeyDown = !wasKeyDown && !isKeyReleased;

Reading the MSDN docs, I really think this should be like:

    bool isKeyDown = wasKeyDown && !isKeyReleased;

i.e. wasKeyDown should not be negated. I tried that and it now works correctly. Don't know full implications of this change, so anyone with more insight is welcome to leave a comment.

**Comment by Shujee** [comment]
More digging revealed that removing the negation operator results in KeyDown event NOT being raised when the key goes down for the first time. I have now changed that line to:

bool isKeyDown = !isKeyReleased;

Things are apparently working fine for me now. I still look forward to original author's comments on the implications of this change.

**Comment by gmamaladze** [comment]
@Shujee Thank you for your investigation. Your change sounds reasonable. Would you please create a pull request on this issue. I'll incorporate it in the next distribution.

**Comment by Shujee** [comment]
I'd love to, but I don't know what a pull request is (i'm not too familiar with GitHub). I went to Pull Requests tab and clicked New Pull Request, but it shows me "master" and "vNext" versions, clicking any of which tells me that there is no difference between it and the base version. Or am I doing something wrong?

**Comment by gmamaladze** [comment]
@Shujee Nevermind. I can also incorporate changes. Otherwise if you still want to get familiar with pull requests just try it out. This documentation will help you https://help.github.com/articles/using-pull-requests/

**Comment by Shujee** [comment]
@gmamaladze  Did you get a chance to incorporate this change?

**Comment by Shujee** [comment]
@gmamaladze Was this change ever incorporated?

**Comment by Shujee** [comment]
OK. I went ahead, committed this change and created a pull request. This is my first time using GitHub Fork/Commit system, so not sure if I have done everything correctly. Can you please tell me when these changes will be published to NuGet?
