### ISSUE TITLE
Formatting e.keydata

### ISSUE THREAD

**Issue by JimmyAppelt** [gmamaladze/globalmousekeyhook#69]
is there a way to format the `e.keydata` within the lib ?

``` c#
if (e.KeyData.ToString() == "A, Shift, Control")
{
   MessageBox.Show($"you pressed {e.KeyData}");
}
```

Would like to compare to `"Ctrl+Shift+A"` instead of `"A, Shift, Control"`

**Comment by gmamaladze** [comment]
See new feature [Detecting Key Combinations and Sequences](https://github.com/gmamaladze/globalmousekeyhook/blob/vNext/keycomb.md)
