### ISSUE TITLE
How to recognize key combinations?

### ISSUE THREAD

**Issue by asim1337** [gmamaladze/globalmousekeyhook#81]
I can't figure out the most obvious function.. How can i recognize key combinations?
I tried:
`
private void M_GlobalHook_KeyPress(object sender, KeyPressEventArgs e)
{
        if (e.KeyChar == (char)0x41 && e.KeyChar == (char)0xA2)
    {
        MessageBox.Show("Left Ctrl + A pressed!");
    }
}
`

**Comment by caschw** [comment]
I'm doing the following in my code to detect shift + caps lock and ctrl+caps lock.
```
// Holding down Shift and CapsLock, not already suspending toggle
if (e.Shift && e.KeyValue == 20){...}
// Holding down Control and Capslock, suspending of toggle active
else if (e.Control && e.KeyValue){...}
```

**Comment by gmamaladze** [comment]
See new feature [Detecting Key Combinations and Sequences](https://github.com/gmamaladze/globalmousekeyhook/blob/vNext/keycomb.md)
