### ISSUE TITLE
Windows key is not considered as a "Modifier"

### ISSUE THREAD

**Issue by jgrossrieder** [gmamaladze/globalmousekeyhook#86]
Hi,

I wanted to use your application to listen to the "Win+O" key combination. 
I did the following:

```
protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            _globalHook = Hook.GlobalEvents();
            _globalHook.KeyDown += _globalHook_KeyDown;
        }

        private void _globalHook_KeyDown(object sender, KeyEventArgs e)
        {
                Console.WriteLine($"Modifiers: {e.Modifiers}, keys: {e.KeyCode}");
        }
```

But it seems that when I press Window+O key, it just have a "LWin" key followed by a "O" key.

**Comment by gmamaladze** [comment]
See new feature [Detecting Key Combinations and Sequences](https://github.com/gmamaladze/globalmousekeyhook/blob/vNext/keycomb.md)
