### ISSUE TITLE
5.6.0 Compile errors

### ISSUE THREAD

**Issue by cvdevol** [gmamaladze/globalmousekeyhook#93]
Compiling with Visual Studio 2015. I get the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1525	Invalid expression term '['	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	39	Active
Error	CS0443	Syntax error; value expected	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	39	Active
Error	CS1003	Syntax error, ',' expected	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	39	Active
Error	CS0305	Using the generic type 'KeyValuePair<TKey, TValue>' requires 2 type arguments	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	39	Active
Error	CS0119	'Combination' is a type, which is not valid in the given context	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	39	Active
Error	CS0119	'Action' is a type, which is not valid in the given context	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	39	Active
Error	CS0103	The name 'element' does not exist in the current context	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	39	Active
Error	CS0103	The name 'element' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	39	Active
Error	CS0103	The name 'var' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	48	Active
Error	CS0103	The name 'element' does not exist in the current context	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	48	Active
Error	CS0103	The name 'element' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	48	Active
Error	CS0103	The name 'Key' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	50	Active
Error	CS0103	The name 'Chord' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	50	Active
Error	CS0103	The name 'All' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	50	Active
Error	CS0103	The name 'Key' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	52	Active
Error	CS0103	The name 'ChordLength' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	52	Active
Error	CS0103	The name 'Key' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	53	Active
Error	CS0103	The name 'ChordLength' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	53	Active
Error	CS0103	The name 'Value' does not exist in the current context.	MouseKeyHook	C:\Users\Kalki\Documents\Visual Studio 2015\Projects\globalmousekeyhook-vNext\MouseKeyHook\KeyCombinationExtensions.cs	54	Active

**Comment by gmamaladze** [comment]
The reason is that I used new c# 7.0 features like inline out parameter. I am considering wether I should move forward and stay with c# 7.0 syntax or adjust it back to build with c# 6.

**Comment by cvdevol** [comment]
Unfortunately, I don't have VS2017 yet. My vote is for c#6. :-)

**Comment by gmamaladze** [comment]
Done. Please pull the newest version from vNext (default branch).

**Comment by cvdevol** [comment]
Thanks!

**Comment by cvdevol** [comment]
Note that this now compiles as version 5.5.0.
